[package]
name = "vsc-contract-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
clap = { version = "4.5.26", features = ["derive"] }
deadpool = "0.12.1"
deadpool-postgres = "0.14.1"
env_logger = "0.11.6"
lazy_static = "1.5.0"
log = "0.4.22"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
serde_json = "1.0.135"
tokio = "1.43.0"
tokio-postgres = { version = "0.7.12", features = ["with-serde_json-1"] }
toml = "0.8.19"
