[package]
name = "vsc-contract-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
clap = { version = "4.5.26", features = ["derive"] }
env_logger = "0.11.6"
lazy_static = "1.5.0"
log = "0.4.22"
postgres = "0.19.9"
serde = { version = "1.0.217", features = ["derive"] }
serde_derive = "1.0.217"
toml = "0.8.19"
